CREATE TABLE [membership].[MemberDetails] (
    [MemberID]                         INT           NOT NULL,
    [FamilyID]                         INT           NOT NULL,
    [TitleTypeID]                      INT           NOT NULL,
    [MemberInitials]                   VARCHAR (15)  NULL,
    [MemberFirstName]                  VARCHAR (150) NULL,
    [MemberMiddleName]                 VARCHAR (100) NULL,
    [MemberLastName]                   VARCHAR (100) NULL,
    [SubscriptionNumber]               VARCHAR (50)  NULL,
    [GenderTypeID]                     INT           NOT NULL,
    [EducationalQualification]         VARCHAR (50)  NULL,
    [Profession]                       VARCHAR (70)  NULL,
    [RelationshipTypeID]               INT           NOT NULL,
    [DateOfBirth]                      DATETIME      NULL,
    [MaritalStatusTypeID]              INT           NOT NULL,
    [AnniversaryDate]                  DATETIME      NULL,
    [Baptised]                         BIT           NOT NULL,
    [BaptismDate]                      DATETIME      NULL,
    [BaptisedChurchAddress]            VARCHAR (150) NULL,
    [Confirmed]                        BIT           NOT NULL,
    [ConfirmationDate]                 DATETIME      NULL,
    [ConfirmedChurchAddress]           VARCHAR (150) NULL,
    [Mobile]                           VARCHAR (20)  NULL,
    [AlternateMobile1]                 VARCHAR (20)  NULL,
    [AlternateMobile2]                 VARCHAR (20)  NULL,
    [Email]                            VARCHAR (70)  NULL,
    [MemberStatusTypeID]               INT           NOT NULL,
    [MemberStatusInactiveReasonTypeID] INT           NULL,
    [EternalLifeDate]                  DATETIME      NULL,
    [Office_Name]                      VARCHAR (100) NULL,
    [Office_DoorFlatNo]                VARCHAR (15)  NULL,
    [Office_BuildingName]              VARCHAR (60)  NULL,
    [Office_StreetName]                VARCHAR (100) NULL,
    [Office_NagarName]                 VARCHAR (60)  NULL,
    [Office_AreaName]                  VARCHAR (50)  NULL,
    [Office_Landmark]                  VARCHAR (100) NULL,
    [Office_City]                      VARCHAR (50)  NULL,
    [Ofice_Pincode]                    INT           NULL,
    [WorkPhone]                        VARCHAR (20)  NULL,
    [WorkEmail]                        VARCHAR (70)  NULL,
    [MembershipSince]                  DATETIME      NULL,
    [AreasOfInterest]                  VARCHAR (200) NULL,
    [Notes]                            VARCHAR (200) NULL,
    [DeclarationAccepted]              BIT           NOT NULL,
    [Timestamp]                        DATETIME      CONSTRAINT [DF_MemberDetails_Timestamp] DEFAULT (getdate()) NULL,
    CONSTRAINT [pkMemberDetails] PRIMARY KEY CLUSTERED ([MemberID] ASC, [FamilyID] ASC),
    CONSTRAINT [fkMemberDetails_TypeFamilyInActiveStatusReason] FOREIGN KEY ([MemberStatusInactiveReasonTypeID]) REFERENCES [membership].[TypeFamilyInActiveStatusReason] ([ID]),
    CONSTRAINT [fkMemberDetails_TypeFamilyStatus] FOREIGN KEY ([MemberStatusTypeID]) REFERENCES [membership].[TypeFamilyStatus] ([ID]),
    CONSTRAINT [fkMemberDetails_TypeGender] FOREIGN KEY ([GenderTypeID]) REFERENCES [membership].[TypeGender] ([ID]),
    CONSTRAINT [fkMemberDetails_TypeMaritalStatus] FOREIGN KEY ([MaritalStatusTypeID]) REFERENCES [membership].[TypeMaritalStatus] ([ID]),
    CONSTRAINT [fkMemberDetails_TypeRelationship] FOREIGN KEY ([RelationshipTypeID]) REFERENCES [membership].[TypeRelationship] ([ID]),
    CONSTRAINT [fkMemberDetails_TypeTitle] FOREIGN KEY ([TitleTypeID]) REFERENCES [membership].[TypeTitle] ([ID])
);



